// Please do NOT edit this file directlly
// To synchronize set/update project configs:
// + From terminal, run $ sheetbase config set key=value|...
// + Or, edit configs in sheetbase.json, then run $ sheetbase config update
export const SHEETBASE_CONFIG = {
   "apiKey": "DfyYHKdjUGnmOFH7hQVdfrbhCGJs2WBJ",
   "databaseId": "1WPJ1vDC6mm4GJXsyTpczk9NP7AS6eDgqhfnHp6HviwA"
}