// Please do NOT edit this file directlly
// To synchronize set/update project configs:
// + From terminal, run $ sheetbase config set key=value|...
// + Or, edit configs in sheetbase.json, then run $ sheetbase config update
export const SHEETBASE_CONFIG = {
   "backendUrl": "https://script.google.com/macros/s/AKfycbyfT_GmHw3-sk6DSVEpyPeX5S76JrkOJNSE6csvZvC4l9lkw3T9tScs4dYo3d_EY59Sbg/exec",
   "apiKey": "DfyYHKdjUGnmOFH7hQVdfrbhCGJs2WBJ",
   "databaseId": "1WPJ1vDC6mm4GJXsyTpczk9NP7AS6eDgqhfnHp6HviwA",
   "databaseGids": {
      "categories": "101",
      "tags": "102",
      "pages": "103",
      "posts": "104",
      "products": "107"
   }
}